// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO8Yv165xtGVchk1cgY_cJfUqMi_Chfbc',
    appId: '1:567556418286:web:6f85da45326a565523a1ff',
    messagingSenderId: '567556418286',
    projectId: 'mandi-price-tracker-dea71',
    authDomain: 'mandi-price-tracker-dea71.firebaseapp.com',
    storageBucket: 'mandi-price-tracker-dea71.firebasestorage.app',
    measurementId: 'G-KRB519QMCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyKuzxQ04K5hn4cqoU14WLThtsWxAcDvU',
    appId: '1:567556418286:android:2e2e3e5cd3b9b93723a1ff',
    messagingSenderId: '567556418286',
    projectId: 'mandi-price-tracker-dea71',
    storageBucket: 'mandi-price-tracker-dea71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp9hA4qf2nxMSc_ljwl8AYT3kpdbQFvEk',
    appId: '1:567556418286:ios:54c7f7a701988c1e23a1ff',
    messagingSenderId: '567556418286',
    projectId: 'mandi-price-tracker-dea71',
    storageBucket: 'mandi-price-tracker-dea71.firebasestorage.app',
    iosBundleId: 'com.example.mandiProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp9hA4qf2nxMSc_ljwl8AYT3kpdbQFvEk',
    appId: '1:567556418286:ios:54c7f7a701988c1e23a1ff',
    messagingSenderId: '567556418286',
    projectId: 'mandi-price-tracker-dea71',
    storageBucket: 'mandi-price-tracker-dea71.firebasestorage.app',
    iosBundleId: 'com.example.mandiProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO8Yv165xtGVchk1cgY_cJfUqMi_Chfbc',
    appId: '1:567556418286:web:5fe6b78cc1dfcf8123a1ff',
    messagingSenderId: '567556418286',
    projectId: 'mandi-price-tracker-dea71',
    authDomain: 'mandi-price-tracker-dea71.firebaseapp.com',
    storageBucket: 'mandi-price-tracker-dea71.firebasestorage.app',
    measurementId: 'G-H8BQ8F93GX',
  );
}
